name: Release WASM (GitHub Pages)
on:
  push:
    tags: ["v*"]

env:
  PUBLIC_URL: /bevy-shell-template/

jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build | Trunk
        run: trunk build --release --public-url ${{ env.PUBLIC_URL }}

      - name: Post Build | Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: ./launchers/wasm/dist/

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Download dist
        uses: actions/download-artifact@v3
      - name: Setup | Place dist
        run: mv ./artifact/ ./launchers/wasm/dist/

      - name: Deploy | Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./launchers/wasm/dist/
